# DaemonSet to configure kernel parameters on all nodes
# Fixes "failed to create fsnotify watcher: too many open files" errors
# Reference: https://kind.sigs.k8s.io/docs/user/known-issues/
# Reference: https://www.scaleway.com/en/docs/kubernetes/reference-content/modifying-kernel-parameters-kubernetes-cluster/
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sysctl-tuning
  namespace: kube-system
  labels:
    app: sysctl-tuning
spec:
  selector:
    matchLabels:
      app: sysctl-tuning
  template:
    metadata:
      labels:
        app: sysctl-tuning
    spec:
      hostNetwork: true
      hostPID: true
      tolerations:
        # Run on all nodes including masters
        - operator: "Exists"
      initContainers:
        - name: sysctl-init
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              echo "Current inotify settings:"
              sysctl fs.inotify.max_user_watches fs.inotify.max_user_instances
              echo "Setting new inotify limits..."
              sysctl -w fs.inotify.max_user_watches=524288
              sysctl -w fs.inotify.max_user_instances=512
              echo "New inotify settings:"
              sysctl fs.inotify.max_user_watches fs.inotify.max_user_instances
          securityContext:
            privileged: true
      containers:
        - name: sleep
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - sleep infinity
          resources:
            requests:
              cpu: 1m
              memory: 4Mi
            limits:
              cpu: 10m
              memory: 16Mi
