# OpenTelemetry Instrumentation CR
# This configures auto-instrumentation for applications
# To enable on a pod, add annotation: instrumentation.opentelemetry.io/inject-<language>: "true"
# Supported languages: java, nodejs, python, dotnet, go
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: default-instrumentation
  namespace: opentelemetry-operator
spec:
  # Send traces to Alloy's OTLP receiver
  exporter:
    endpoint: http://alloy.alloy.svc.cluster.local:4317

  # Propagators for context propagation
  propagators:
    - tracecontext
    - baggage
    - b3

  # Sampler configuration - sample everything for homelab
  sampler:
    type: always_on

  # Java auto-instrumentation settings
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
    env:
      - name: OTEL_INSTRUMENTATION_COMMON_EXPERIMENTAL_CONTROLLER_TELEMETRY_ENABLED
        value: "true"

  # Node.js auto-instrumentation settings
  nodejs:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:latest

  # Python auto-instrumentation settings
  python:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:latest

  # .NET auto-instrumentation settings
  dotnet:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet:latest

  # Go auto-instrumentation settings (requires eBPF, may need privileged)
  go:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-go:latest

  # Environment variables injected into all instrumented pods
  env:
    - name: OTEL_SERVICE_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.labels['app.kubernetes.io/name']
    - name: OTEL_K8S_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: OTEL_K8S_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: OTEL_K8S_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "k8s.cluster.name=hetzner-cluster-1"
