{{- if .Values.opentelemetryOperator.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      chart: opentelemetry-operator
      targetRevision: {{ .Values.opentelemetryOperator.chartVersion }}
      helm:
        valueFiles:
          - $values/opentelemetry-operator/values.yaml
    - repoURL: https://github.com/dthackray/hetzner-lab.git
      targetRevision: main
      ref: values
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: opentelemetry-operator
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs
    - group: apps
      kind: Deployment
      jqPathExpressions:
        - .status
    - group: apps
      kind: ReplicaSet
      jqPathExpressions:
        - .status
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
{{- end }}
