{{- if .Values.tempo.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: tempo
      targetRevision: {{ .Values.tempo.chartVersion }}
      helm:
        valueFiles:
          - $values/tempo/values.yaml
    - repoURL: https://github.com/dthackray/hetzner-lab.git
      targetRevision: main
      ref: values
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: tempo
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jqPathExpressions:
        - .status
        - .spec.volumeClaimTemplates[]?.metadata
        - .spec.volumeClaimTemplates[]?.status
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
{{- end }}
