{{- if .Values.wikimediaProducer.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wikimedia-producer
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    # Deploy after Kafka cluster
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/dthackray/hetzner-lab.git
    targetRevision: main
    path: wikimedia-producer
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
