---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-postgresql
  namespace: authentik
spec:
  encryptedData:
    password: AgBL4EBrvO42OPMx0XMGOnCt6eLh3KKff8l5bU5SnFzIby+ViHdDn2gUbbYmf6tsFynUT3vyWc2KLHI3cM7LPfwBUPpKd6gTVRHl+HvAFYLE/Nkee2Ci5bTYuZ31etgshP6D4adKsogsNaCnRVvwb7kfjfrIYtm6Kbt8ENilco8U2ghlaIy+3dMpDGsdJeMayNyuf8d6UvYMOEdva/Uay8lYSaOZcDeJT9VeBbZFTrfZsSzWgfk8iJfT/6HBBLZceq0hy6O4bD2oXtuDWyUE0xmI63SdVVgQ9N1cOoNNeyGNaWZQIodnce1n7N+8eCt+uArnRn7nZ4CVGnxDEqRAQXweH3Hs4u4j+JW16gYBtzfpk58IRrEdvivk83bfVzf1TGqTkJZsbU+orTYeWgyVXj31NRqw05NCRE+gfBTcnUsjE+yXkdgeCY8sHTE09xCI/iY+DlhxwnfPrAfaYc1Hyf0pDje481EliIaZaP61hYx4IdD0/+FMn5WZ+s0UgAzdmIlmPM12EAFki4ogIyMuJ/9OB/dWYbSKqPXx3WEfshsI7dbLclnmFhbg1S6EMvUS5mCm+6zFxzNI4DIRQSxp7bsYfA5Lnd0TxoATslTASUT7Dm391Ze5+BMyw0TR/9pCnLMq9vX/l4rzFmLSsZ5o8oLuXb9jBCStnYfuy4GIZrnu7ztFDSc2dkD9LdqBXkA8Kuj9ynPJA2fF3j0igqRj8MeC1x7HpL42q/tXvhxOhXrTmw==
    postgres-password: AgAKKzOeyuJQ6bwIJB12qOS7b9YgXLizxE/vD4M6Q/ICDeklAIYjVXxcRxAPGtyrn8bGEWwM2DqvF+F93KDc7w25xNtnhn4mzlQz2Le8o+PbtDO4n9lUVCk5O0PWABKc5C769s3gd7A+2piptEhyqLg6c9IZp1J5Th7O1s2PZMKDGe6bmS6S/bnBwBSTLPM5lNd4DiRa9tZ8BWZ56iZmMVtyoNTg4s7bdwgvBWj2ZhQF8kP69UxgaxdDFqyXtxrMYwszxDLEMxOd4EXpAAYQ5FXaSvL5JGV7PZWVYW+ZnBnJmFTMpABq2LA62nv/eLa7r2ET1y8Omm6JzVqkrHef7UgRinXLR7h3753Z0g0JsilA3ubDRejXtBpusQJMXw95PKu3VzAJ1ed6LAnygVza+aUeeG0LwPoJ4x99xshX00mP7jGJ+wTWl4TmMR5/egFI+Cb6W2U3K/KaUiVgMOUt72RkBIEe0VbYXziYogZ3/6aYLJ20I0UKFRtETU0ksduq9EPQ4o8IsC8p/3bQLhi5tIE/WG2ZN+wkJ/uQqE5eGmDg6eyg3oFZtTuwaQu2/9dvhqS6wrv7s/jd9r0hoye8zE2rn7PzJKYphWNmKSx/dR9ZVVZnNENAE2NDsSbWiKTupx7EitipqOYqMba0HEDAVJijv9r/W+i79RZyjwaIpDDL2/iumlTkhvfPyJS32kCmjd+foRV+JHo0mhAMu5ODqCVgaXKQfusnMNYNv7RsUa/i0w==
  template:
    metadata:
      name: authentik-postgresql
      namespace: authentik
