apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Let's Encrypt staging server for testing
    # Rate limits are much higher than production
    server: https://acme-staging-v02.api.letsencrypt.org/directory

    # Email address for ACME registration and renewal notifications
    email: djthackray@gmail.com

    # Secret to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging

    # DNS-01 challenge solver using Cloudflare
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
