apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Let's Encrypt staging server for testing
    # Rate limits are much higher than production
    server: https://acme-staging-v02.api.letsencrypt.org/directory

    # Email address for ACME registration and renewal notifications
    email: djthackray@gmail.com

    # Secret to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging

    # HTTP-01 challenge solver using Traefik ingress
    solvers:
    - http01:
        ingress:
          class: traefik
